import React from 'react';
import { Helmet } from 'react-helmet-async';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { Link } from 'react-router-dom';
import Breadcrumbs from '@/components/seo/Breadcrumbs';

const FlightBookingFAQ = () => {
    const faqs = [
        // SECTION 1: FLIGHT BOOKING BASICS
        {
            question: "What is flight ticket booking and how does it work?",
            answer: "Flight ticket booking is the process of purchasing a seat on an aircraft for travel between destinations. It operates through specific inventory classes or 'fare buckets'. When you book a ticket, your details are recorded in the airline's Central Reservation System (CRS), generating a PNR (Passenger Name Record). This confirmation ensures your seat is reserved. The price you see depends on the availability of these fare buckets—cheaper buckets sell out first, leaving only higher-priced seats. Booking involves selecting your route, confirming passenger details, making payment, and receiving an e-ticket which allows you to enter the airport and obtain a boarding pass."
        },
        {
            question: "What details are required to book a flight ticket?",
            answer: "To book a domestic flight in India, you primarily need the passenger's full name exactly as it appears on their government ID, their gender, and a valid mobile number and email address for communication. For infants (under 2 years), the Date of Birth is strictly required to calculate fares. For international flights, the requirements are more stringent: you must provide specific passport details (Passport Number, Expiry Date, Issuing Country) and often valid visa details depending on the destination. Ensuring these details match your documents is critical, as even minor spelling errors can lead to boarding denial."
        },
        {
            question: "What is a PNR number in flight booking?",
            answer: "A PNR (Passenger Name Record) is a unique alphanumeric code, usually 6 characters long (e.g., 'XJ59LM'), generated by the airline's system. It acts as the digital fingerprint for your journey. Unlike a mere reference number, the PNR contains your itinerary, passenger details, contact info, and special service requests. You need this code to web check-in, check your flight status, manage your booking, or process cancellations. Even if you book through an agent like Rudraksh Safar, the airline's PNR is the ultimate source of truth for your travel."
        },
        {
            question: "What is the difference between one-way, round-trip, and multi-city flights?",
            answer: "A 'One-Way' ticket covers travel from Point A to Point B only. It is best for uncertain return plans. A 'Round-Trip' includes the return journey (A to B and back to A) on a single ticket. Round-trip fares are often cheaper than booking two separate one-way tickets because airlines incentivize securing both legs of your journey. 'Multi-City' bookings allow you to fly A to B, then C to D, or have stopovers. Complex multi-city itineraries can be tricky to price online; this is where an experienced agent can manually construct a fare that saves you money compared to automated systems."
        },
        {
            question: "Is it cheaper to book flights online or through an agent?",
            answer: "This is a common dilemma. While online portals show 'base fares', they often add convenience fees, meal charges, and insurance costs at checkout. Authorized agents like Rudraksh Safar often have access to 'consolidator fares' or corporate inventory that isn't visible to the public. More importantly, booking through an agent provides a safety net. If a flight is cancelled or you need a refund, you call us directly—you don't waste hours chatting with a bot. For international flights, complex layouts, or group bookings, an agent is almost always cheaper and safer than valid DIY attempts."
        },

        // SECTION 2: DOMESTIC FLIGHT BOOKING
        {
            question: "How can I book domestic flight tickets in India?",
            answer: "You can book domestic flights via airline websites, online travel aggregators, or authorized travel agents. In India, major carriers like IndiGo, Air India, Vistara, and Akasa connect all major cities. Booking involves searching for your route, selecting a flight based on time and price, entering passenger details, and paying. While online options are plentiful, booking through a local agent in Bhilai or Raipur ensures you have a human point of contact for any post-booking modifications, which is invaluable if your plans change."
        },
        {
            question: "What are the cheapest days to book domestic flights?",
            answer: "The 'Tuesday is cheapest' rule is largely a myth in the modern era of dynamic pricing algorithms. In reality, flight prices are driven by demand and time-to-departure. Generally, booking mid-week (Tuesday or Wednesday) for travel on mid-week days is cheaper than weekends because business travel demand is lower. However, the most effective way to get cheap fares is simply booking 21-30 days in advance. Last-minute bookings (within 7 days) are almost always the most expensive, regardless of the day of the week."
        },
        {
            question: "How early should domestic flights be booked?",
            answer: "For standard travel, the 'sweet spot' is 15 to 30 days before departure. This is when airlines typically release favorable fare buckets. If you are traveling during peak seasons like Diwali, Chhath Puja, or Summer Vacations, you should book 45-60 days in advance. Waiting for a 'last-minute drop' is risky; in India's high-demand routes, prices usually skyrocket as the date approaches rather than dropping."
        },
        {
            question: "What documents are required for domestic flights?",
            answer: "For domestic air travel in India, every passenger (including children) must present a valid government-issued photo ID. Acceptable documents include Aadhaar Card, Voter ID, Driving License, Pan Card, or Passport. For infants, a Birth Certificate is required to prove age. You do not need a physical ticket printout; a soft copy on your mobile or the digital boarding pass along with your original ID is sufficient for entry into the terminal."
        },
        {
            question: "Can I reschedule or cancel domestic flight tickets?",
            answer: "Yes, but policies depend heavily on the 'Fare Family' you chose—Savings, Flexi, or Corporate. Standard 'Savings' fares usually attract a notification cancellation fee (often ₹3000-₹3500) plus the fare difference for rescheduling. 'Flexi' fares offer free changes but cost more upfront. If you booked through an agent, we can process these changes instantly for you, often navigating the waivers better than an automated online system can."
        },

        // SECTION 3: INTERNATIONAL FLIGHT BOOKING
        {
            question: "How do international flight bookings work?",
            answer: "International booking is more complex involving strict adherence to immigration rules. It requires a valid passport (usually with 6 months validity from return date) and often a visa. The booking process connects multiple global distribution systems (GDS). Baggage allowances are higher (often 23kg-30kg), and check-in times are 3-4 hours prior. Unlike domestic flights, names must match the passport character-for-character, as discrepancies can lead to deportation or boarding denial."
        },
        {
            question: "What documents are required for international flights?",
            answer: "Mandatory documents include: 1) Original Passport with 6-month validity. 2) Valid Visa for the destination (or E-Visa/ETA). 3) Return or Onward ticket (proof of return is required by immigration). 4) Sometimes, proof of accommodation (Hotel Booking). 5) Transit visas if you are changing planes in certain countries over long durations. Always check standard health or vaccination requirements for your specific destination."
        },
        {
            question: "How early should international flights be booked?",
            answer: "Ideally, international flights should be booked 2 to 3 months in advance. This period usually offers the most stable 'Economy Standard' fares. For travel during peak holidays (Christmas, New Year, Student Season in August), booking 4-5 months ahead is recommended. Unlike domestic flights, international inventory is managed globally, so seats vanish quickly as travelers from all over the world compete for the same routes."
        },
        {
            question: "What is a transit flight and layover?",
            answer: "A transit flight involves changing planes at an intermediate airport (the Hub) to reach your destination. The period you wait at the airport is the 'layover'. Start flights often require you to stay inside the terminal (airside transit). If the layover is very long (e.g., 8+ hours) or requires changing terminals that are not connected airside, you might need a 'Transit Visa' to enter that country fast. Agents check these transit rules carefully to ensure you don't get stuck."
        },
        {
            question: "Are international flights refundable?",
            answer: "It depends on the fare class. 'Promo' or 'Saver' economy tickets are often non-refundable or have high cancellation penalties. 'Flex' or 'Standard' fares allow refunds with a deduction. Taxes (which can be a significant part of the ticket) are usually refundable even on non-refundable tickets, but airlines often make claiming this difficult for individuals. Booking via an agent ensures you get back whatever portion of the fare is legally claimable."
        },

        // SECTION 4: FLIGHT BOOKING FROM BHILAI / RAIPUR
        {
            question: "Which airport should I use if I live in Bhilai?",
            answer: "Swami Vivekananda Airport (RPR) in Raipur is the primary airport for Bhilai, Durg, and Raipur residents. It is situated in Mana, approximately 45-50 km from Bhilai. The travel time via NH-53 is usually 60-90 minutes depending on traffic. It is the best-connected airport in Chhattisgarh, handling daily flights to all major Indian metros."
        },
        {
            question: "Are there direct flights from Raipur?",
            answer: "Yes, Raipur (RPR) has excellent direct connectivity. You can fly non-stop to Delhi, Mumbai, Hyderabad, Kolkata, Bangalore, and Indore. For international destinations or other domestic cities, you typically take a connecting flight via Delhi or Mumbai. The connectivity has improved significantly, making international travel from Raipur much smoother than before."
        },
        {
            question: "Is it cheaper to fly from Raipur or Nagpur?",
            answer: "Nagpur (NAG) is a larger international airport and sometimes offers more direct connections or slightly cheaper fares for specific sectors. However, Nagpur is 260 km from Bhilai (4-5 hours by road/train). Unless the fare difference is massive (₹3000+ per person) or the connectivity is unique, flying from Raipur is usually more cost-effective when you factor in the travel time, fuel, and fatigue of reaching Nagpur."
        },
        {
            question: "Do you book flights for Bhilai, Durg & Raipur residents?",
            answer: "Yes, Rudraksh Safar specializes in serving clients from Bhilai, Durg, and Raipur. We understand the specific transit times needed to reach Mana Airport from Sector areas or Durg. We can help plan your itinerary accounting for local traffic conditions, ensuring you never miss a flight. We also provide support for web check-in so you can head straight to security."
        },
        {
            question: "Can you arrange airport pickup from Bhilai to Raipur?",
            answer: "Yes, we can arrange reliable <a href='/faqs/cab-booking' class='text-primary hover:underline'>Cab Services</a> for airport drops and pickups. We ensure the driver is aware of flight timings. This is an optional add-on service we provide to ensure your journey from your doorstep to the destination is seamless."
        },

        // SECTION 5: CHEAP FLIGHTS & SAVING MONEY
        {
            question: "How can I find the cheapest flight tickets?",
            answer: "Flexibility is key. If you can fly mid-week or take early morning/late night flights, you will save money. Booking 25+ days in advance is the golden rule. Additionally, letting an agent monitor prices for you works wonders—we can hold a seat (time-limit booking) when we see a dip, securing the fare before it jumps up again."
        },
        {
            question: "Do flight prices change every day?",
            answer: "Yes, airline pricing is 'dynamic'. Prices can change multiple times a day based on search volume, available seats, and competitor pricing. This is why you might see a price of ₹4000 in the morning and ₹5200 by evening. Our systems allow us to see real-time inventory, helping us advice you on whether to book immediately or wait."
        },
        {
            question: "Are last-minute flights cheaper?",
            answer: "This is a widespread myth. In 95% of cases, last-minute flights (booked 0-3 days before travel) are significantly more expensive. Airlines know urgency is high, so algorithms spike the prices. Rarely, if a flight is very empty, a slightly lower fare might appear, but relying on this is extremely risky for critical travel."
        },
        {
            question: "What are red-eye flights and are they cheaper?",
            answer: "Red-eye flights depart late at night (after 11 PM) and arrive early morning (before 5 AM). Because these timings are inconvenient for sleep, they are often cheaper than prime-time morning or evening flights. If you are budget-conscious and can manage the fatigue, they are a great way to save money."
        },
        {
            question: "Can agents get cheaper flight fares?",
            answer: "Often, yes. Agents have access to SME (Small Medium Enterprise) fares, Coupon Fares, or Fixed Departure blocks that are not available on public websites. Especially for group bookings or complicated multi-leg journeys, an agent can construct an itinerary that is cheaper than stitching together single tickets online."
        },

        // SECTION 6: BAGGAGE, CHECK-IN & SEATS
        {
            question: "What is baggage allowance in flights?",
            answer: "For most domestic economy flights in India, the standard check-in allowance is 15 kg/person and cabin baggage is 7 kg. Air India often offers 20-25 kg. For international flights, it varies wildly—some offer 23kg (1 piece), others 46kg (2 pieces). Always check your specific ticket rules. 'Lite' or 'Hand-baggage only' fares have zero check-in allowance."
        },
        {
            question: "What happens if my baggage exceeds the limit?",
            answer: "You will be charged an 'Excess Baggage Fee' at the airport, which is very expensive (approx ₹500-₹1000 per kg domestic). If you know you will carry extra, buying pre-paid excess baggage via an agent or online is 20-30% cheaper than paying at the counter."
        },
        {
            question: "How early should I reach the airport?",
            answer: "For domestic flights from Raipur, reaching 90 minutes (1.5 hours) before departure is safe. For international flights, or flying from major hubs like Delhi/Mumbai, you should reach 3 to 4 hours prior. Security queues and immigration checks can be unpredictable."
        },
        {
            question: "What is web check-in?",
            answer: "Web check-in confirms your presence on the flight digitally 24-48 hours before departure. It is now mandatory for most airlines in India. You select your seat, declare health status, and get a boarding pass. If you don't do it, airlines may charge a facilitation fee at the counter."
        },
        {
            question: "Can I choose my seat in advance?",
            answer: "Yes, during web check-in. Most preferred seats (Window, Aisle, Front Row) are now paid extras. However, airlines usually leave some middle seats or rear seats for free selection. If you want a specific seat, it is best to pay and reserve it early."
        },

        // SECTION 7: CANCELLATION, REFUND & ISSUES
        {
            question: "How long does flight refund take?",
            answer: "If you paid via an agent, the refund timeline depends on the airline processing it back to the agent's account, usually 3-7 working days. If you booked directly, it goes to your card. Note that 'Processing' takes time; the money doesn't reflect instantly upon clicking cancel."
        },
        {
            question: "What happens if my flight is cancelled by airline?",
            answer: "If the airline cancels the flight, you are entitled to a full refund without any cancellation penalties. Alternatively, they must accommodate you on the next available flight at no extra cost. Always demand 'Full Refund' options if the alternative flight doesn't suit your schedule."
        },
        {
            question: "Can name be corrected on flight ticket?",
            answer: "Minor phonetic corrections (e.g., 'Smyth' to 'Smith') *might* be allowed by airlines for a fee, but it's discretionary. Complete name changes (swapping Person A for Person B) are strictly prohibited. You would have to cancel and rebook. Always double-check spellings before paying."
        },
        {
            question: "What if I miss my flight?",
            answer: "If you are a 'No-Show', the entire ticket value is usually forfeited, except for some airport taxes which are negligible. Some 'Flexi' fares might allow rebooking for a fee. If you know you're running late, call the agent/airline immediately *before* departure; sometimes they can reschedule you for a fee, saving the base fare."
        },
        {
            question: "Are flight tickets transferable?",
            answer: "No. Flight tickets are non-transferable documents. You cannot buy a ticket for yourself and then sell or give it to a friend. The passenger name on the ticket must match the traveler's ID proof."
        },

        // SECTION 8: WHY BOOK WITH YOU
        {
            question: "Why should I book flights through Rudraksh Safar?",
            answer: "We bring the human touch to digital travel. Unlike faceless apps, we are your local partners in Bhilai/Raipur. We handle web check-ins, monitor flight timings, assist with refunds, and ensure you have the right documents. If a problem arises, you call our personal mobile number, not an endless IVR loop."
        },
        {
            question: "Do you book group or corporate flights?",
            answer: "Yes! We specialize in Group Fares for weddings, college tours, and corporate events. Group fares (for 10+ passengers) have different rules and can offer better flexibility on name changes and deposits compared to individual bookings."
        },
        {
            question: "Do you help with visa + flight together?",
            answer: "Absolutely. For international travel, the flight and visa are interconnected. We ensure your flight dates align perfectly with your <a href='/faqs/visa-services' class='text-primary hover:underline'>Visa Validity</a>. We can handle the entire package seamlessly."
        },
        {
            question: "Can you book flights with tour packages?",
            answer: "Yes. Our <a href='/tour-packages-from-bhilai' class='text-primary hover:underline'>Holiday Packages</a> often include flights. Bundling them allows us to synchronize your arrival with hotel check-in times and cab pickups, ensuring a zero-wait experience."
        },
        {
            question: "How can I contact you for urgent flight booking?",
            answer: "For instant bookings, itinerary changes, or emergencies, please WhatsApp or call us directly. We prioritize urgent requests to get you airborne as quickly as possible. Visit our <a href='/contact' class='text-primary hover:underline'>Contact Page</a> for details."
        }
    ];

    // Schema Generation
    const faqSchema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": faqs.map(faq => ({
            "@type": "Question",
            "name": faq.question,
            "acceptedAnswer": {
                "@type": "Answer",
                "text": faq.answer
            }
        }))
    };

    return (
        <>
            <Helmet>
                <title>Flight Booking FAQs | Domestic & International Air Tickets Bhilai</title>
                <meta name="description" content="Expert answers on flight booking, baggage rules, cancellations, and best fares from Bhilai/Raipur. Your local travel agent guide to stress-free air travel." />
                <meta name="keywords" content="flight booking bhilai, flight ticket agent bhilai, cheap flights from raipur, international flight booking india, air ticket agency durg" />
                <link rel="canonical" href="https://rudrakshsafar.com/faqs/flight-booking" />
                <script type="application/ld+json">
                    {JSON.stringify(faqSchema)}
                </script>
            </Helmet>

            <Navbar />

            <main className="min-h-screen bg-background text-foreground">
                {/* Hero Section */}
                <section className="relative bg-primary/5 py-16">
                    <div className="container mx-auto px-4">
                        <Breadcrumbs items={[
                            { label: 'Home', path: '/' },
                            { label: 'FAQs', path: '/faqs' },
                            { label: 'Flight Booking', path: '/faqs/flight-booking' }
                        ]} />
                        <div className="mt-8 max-w-4xl">
                            <h1 className="text-4xl md:text-5xl font-bold text-primary mb-6">
                                Flight Booking <span className="text-secondary">FAQs</span>
                            </h1>

                            {/* Mandatory Intro - 300+ words context */}
                            <div className="prose prose-lg dark:prose-invert text-muted-foreground leading-relaxed">
                                <p>
                                    Flight booking is often seen as a simple click-and-book process, but beneath the surface, it involves a complex network of dynamic pricing algorithms, inventory classes, and strict aviation regulations. Whether you are flying domestically from Raipur or planning an international trip to Europe or Asia, understanding how air ticketing works can save you significant money and stress.
                                </p>
                                <p>
                                    Prices for flight tickets fluctuate wildly based on supply and demand, fuel costs, and even the browser cookies on your device. What looks like a cheap fare on an aggregator site often balloons with hidden fees at checkout. Furthermore, the difference between domestic and international bookings is vast—international travel requires precise documentation, visa alignment, and adherence to transit rules that do not apply to domestic sectors. A simple name spelling error that is overlooked on a train ticket can result in being denied boarding on an international flight.
                                </p>
                                <p>
                                    This is where <span className="font-semibold text-foreground">Local Agent Support</span> becomes a game-changer for residents of Bhilai, Durg, and Raipur. While online portals are convenient for simple one-way trips, they lack accountability when things go wrong. If a flight is cancelled, baggage is lost, or a connection is missed, having a local expert like Rudraksh Safar means you have a human advocate handling the airline bureaucracy for you. We understand the specific logistics of traveling from Chhattisgarh—flight timings from Swami Vivekananda Airport (RPR), connection buffers needed in Delhi/Mumbai, and the most reliable carriers for our specific region.
                                </p>
                                <p>
                                    We believe that an informed traveler is a smart traveler. This comprehensive FAQ guide covers everything from the basics of PNRs and baggage allowances to the nuances of finding the cheapest fares and managing cancellations. Read on to master the art of air travel booking.
                                </p>
                            </div>
                        </div>
                    </div>
                </section>

                {/* Content Section */}
                <section className="py-12">
                    <div className="container mx-auto px-4 max-w-4xl">
                        <div className="space-y-12">
                            {faqs.map((faq, index) => (
                                <div key={index} id={`faq-${index}`} className="group border-b border-border/40 pb-8 last:border-0 scroll-mt-24">
                                    <h2 className="text-2xl font-semibold text-foreground mb-4 flex items-start gap-3">
                                        <span className="text-secondary text-xl mt-1">#</span>
                                        {faq.question}
                                    </h2>
                                    <div
                                        className="text-muted-foreground leading-relaxed text-lg pl-8 prose prose-gray max-w-none dark:prose-invert"
                                        dangerouslySetInnerHTML={{ __html: faq.answer }}
                                    />
                                </div>
                            ))}
                        </div>

                        {/* CTA Section */}
                        <div className="mt-16 bg-primary/10 rounded-2xl p-8 text-center border border-primary/20">
                            <h3 className="text-2xl font-bold mb-4">Need the Lowest Airfare Quote?</h3>
                            <p className="text-muted-foreground mb-6">
                                Don't rely on algorithms. Let our experts find you the best flight deals from Raipur.
                            </p>
                            <div className="flex flex-wrap gap-4 justify-center">
                                <Link to="/contact" className="bg-primary text-white px-8 py-3 rounded-full font-semibold hover:bg-primary/90 transition-colors">
                                    Contact Us
                                </Link>
                                <Link to="/flight-booking-bhilai" className="bg-white text-primary border border-primary px-8 py-3 rounded-full font-semibold hover:bg-primary/5 transition-colors">
                                    Book Flights Now
                                </Link>
                            </div>
                        </div>
                    </div>
                </section>
            </main>

            <Footer />
        </>
    );
};

export default FlightBookingFAQ;
